ws: "ws://127.0.0.1:3001"
http: "http://127.0.0.1:3000"
开关: true
信息传入游戏: true
信息传入QQ: true
# 群号列表
群号:
  - "288526441"
  - "654321"

# 消息格式配置
格式:
  ToQQ: "[MC] %player%: %message%"
  ToMC: "[QQ] %groupName% %name%: %message%"
  # MC的信息可以有颜色代码&
  # %user% -- QQ号
  # %message% -- 信息
  # %name% -- 群聊名字
  # %groupID% -- 群号
  # %groupName% -- 群名(需http)

替换信息:
  图片: "[图片]"
  表情: "[表情]"
  mface: "[某不知名图]" # 懒得测试了
  艾特: "[艾特]"
  群公告等json: "[群公告]"
  视频: "[视频]"
  文件: "[文件]"