正向ws: "ws://127.0.0.1:3001"

踢出玩家: |
  您已被踢出服务器。
  请联系管理员了解详情。
  谢谢！

群号:
  - "123456"
  - "114514"

防下线:
  bool: false
  group: ""
  time: 35 # 分钟  为了防止被傻逼腾讯摸到规律 上下延迟5分钟
  message: "每日活跃"
群管:
  入群欢迎:
    开关: false
    提示词: "%艾特% 欢迎"
  退群解绑:
    开关: false
  进群验证:
    全局验证码过期时间: 5 # 单位 分钟 整数
    固定:
      开关: false
      验证码: "我不是机器人"
      提示词: "请在 %time% 分钟内输入：验证 %code% 以完成验证，否则将被移出群聊。"
    随机:
      开关: false
      提示词: "请在 %time% 分钟内输入验证码：验证 %code% ，否则将被移出群聊。"
      # 数字+字母组合的6位验证码
  验证:
    指令: "验证 "

主人:
  QQ:
    - "2368834255"
    - "2139145308"
  不是主人: "你想怎样"

设置群员名称:
  开关: false
  格式: "超级帅的%id%" # %id% = 玩家ID

绑定:
  开关: true
  指令: "绑定 "
  提示: "%艾特% ID绑定成功"
  QQ重复: "您的QQ已在白名单中，如ID错误，请联系管理员进行处理"
  ID重复: "您的ID已在白名单中！"
  查看绑定: "我的绑定"
  查看: "绑定的ID是: %ID%\n用户: %QQ%"

  查看他人: true
  查看他人命令: "他人绑定 "
  是否at: true # true -> 保留原查看时的格式 如 他人绑定 @某某，则不变
  # false -> 无论是at查还是QQ查 都转化为QQ号
删除ID:
  开关: true
  指令: "删除ID "
  不存在: "该ID不存在"
  提示: "该ID已被删除"

服务器状态:
  开关: true
  是否允许玩家使用: true
  指令: "服务器状态"
  # BungeeCord仅获取玩家数量
  format: "在线玩家: %player_format%"
  nullPlayer: "  无人"

删除QQ:
  开关: true
  指令: "删除QQ "
  提示: "该QQ已被删除"
  不存在: "该QQ不存在"

菜单:
  开关: true
  指令: "菜单"
  菜单: |
    请前往mcqqrun/config.yml修改
